### ISSUE TITLE
Unrelated Issue but...

### ISSUE THREAD

**Issue by Raltyro** [loypoll/OpenTower#1]
This is a completely unrelated issue to the repository but gotta ask

why do you keep trying honestly? i don't meant it harsh, there is clearly an evidence exposing you or somewhat, and you also tried to token log me, but even so, why?

**Comment by loypoll** [comment]
What?

**Comment by Raltyro** [comment]
There is completely an website about exposing you, i thought your already aware about it (idrk if you own the website really but i doubt it)

**Comment by Raltyro** [comment]
Moved convos to discord
unrelated issue anyway mb

**Comment by Raltyro** [comment]
guh

**Comment by loypoll** [comment]
Leave off Discord stuff clean for the love of god
