### ISSUE TITLE
spr_wartimer_font2 is messed up

### ISSUE THREAD

**Issue by Nestomiau** [loypoll/OpenTower#12]
The spr_wartimer_font2 x and y origin is messed at 17,36 when it shoud've been at 0,0.

**Comment by loypoll** [comment]
![image](https://github.com/loypoll/OpenTower/assets/67049420/e5c1b63d-4b68-4862-82a6-a2b70527f523)

**Comment by loypoll** [comment]
You have to use an older LTS 2022 runtime. I've updated the README specifying which one.
The newer version changed something related to sprite offsets and fonts.
