### ISSUE TITLE
(probably obj_screensizer) has a problem making every fonts misplaced

### ISSUE THREAD

**Issue by ghost** [loypoll/OpenTower#15]
![image](https://github.com/loypoll/OpenTower/assets/122388551/5f3b36a1-f7c1-4c50-b0d8-0f99d707844c)
obj_screensizer has a problem making every fonts misplaced like the timer and buttons

Screenshot:
https://cdn.discordapp.com/attachments/1133785508137414818/1219558312291598377/image.png?ex=660bbd2f&is=65f9482f&hm=88cb9481adb9ee02fec2fda525e11f3d68c3c0f218179497b4124e995cf6bdf3&

**Comment by loypoll** [comment]
Read the README please. You're using the wrong runtime

**Comment by WardzzXD** [comment]
> Read the README please. You're using the wrong runtime
oh my bad
