### ISSUE TITLE
obj_parrallax is fucked up

### ISSUE THREAD

**Issue by BreadGuyPT** [loypoll/OpenTower#22]
![image_2024-06-29_171700306](https://github.com/loypoll/OpenTower/assets/146660211/c455e76c-f01d-41bd-9380-dc128664310c)
it's uhhhhh really fucked up

**Comment by LeSpaghettiMaster** [comment]
![image](https://github.com/loypoll/OpenTower/assets/147277520/29a3ba90-3169-4cf9-b51d-d48782503547)
