### ISSUE TITLE
"false state" issue

### ISSUE THREAD

**Issue by namenotf0und404** [loypoll/OpenTower#7]
when the player touches an outlet while in their invincibility frames they go into a bump state, creating wood debris and playing the knight loss sound
![image](https://github.com/loypoll/OpenTower/assets/109756649/5c207c1b-8104-47fc-8aed-090a6fd82bff)

**Comment by loypoll** [comment]
Does this happen in the base game?

**Comment by namenotf0und404** [comment]
rn imma test

**Comment by namenotf0und404** [comment]
ok it doesnt

**Comment by loypoll** [comment]
Fixed in 6ee7036f517b4a0b9037cbcd49199a9a2597819d

**Comment by namenotf0und404** [comment]
ok thank you
