### ISSUE TITLE
"Failed to load image" for almost every single sprite when running

### ISSUE THREAD

**Issue by ryboy111** [loypoll/OpenTower#9]
When i attempt to run the game, it says
"could not open file D:\yes\OpenTower-main\OpenTower-main\sprites\insertspritenamehere\0.png, using blank 16x16 replacement : Could not find file 'D:\yes\OpenTower-main\OpenTower-main\sprites\insertspritenamehere\0.png'."

"Failed to load image D:\yes\OpenTower-main\OpenTower-main\sprites\insertspritenamehere\0.png"

but, the issue is that all of the folders and images exist in that folder, so im very confused. It may just be that i have never messed with actual gamemaker before, but i have followed all the instructions correctly and it doesnt work.

**Comment by loypoll** [comment]
Read the README
